services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: evgenia-art-portfolio
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - PORT=3000
      - HOST=0.0.0.0
    env_file:
      - .env
    volumes:
      # Use named volumes for logs to prevent permission issues
      - app_logs:/app/logs
      - app_sessions:/app/sessions
      - ./public/data:/app/public/data
    healthcheck:
      test: ['CMD', 'wget', '--no-verbose', '--tries=1', '--spider', 'http://localhost:3000/health']
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - app-network
    expose:
      - '3000'

  nginx:
    image: nginx:alpine
    container_name: evgenia-art-nginx
    restart: unless-stopped
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/sites-enabled:/etc/nginx/sites-enabled:ro
      # Option 1: For local development with certificates in repo
      - ./certs:/etc/nginx/certs:ro
      # Option 2: For production server with system certificates
      # Uncomment these lines when deploying to production server
      # - /etc/ssl/certs:/etc/ssl/certs:ro
      # - /etc/ssl/private:/etc/ssl/private:ro
      - ./nginx/logs:/var/log/nginx
    depends_on:
      - app
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  app_logs:
  app_sessions:
