services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: evgenia-art-portfolio
    restart: unless-stopped
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=development
      - PORT=3000
    env_file:
      - .env
    volumes:
      # Persistent data volumes
      - ./logs:/app/logs
      - ./sessions:/app/sessions
      - ./public/data:/app/public/data
      # For development, uncomment these to enable hot reload
      # - ./src:/app/src:ro
      # - ./public:/app/public:ro
      # - ./admin:/app/admin:ro
      # - ./*.html:/app:ro
    healthcheck:
      test: ['CMD', 'wget', '--no-verbose', '--tries=1', '--spider', 'http://localhost:3000/health']
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
